[package]
name = "fueler-upper"
version = "0.1.0"
authors = ["Sven Ewers <sven.ewers@bearlydigital.dev>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.0"